### ISSUE TITLE
Code Completion does not work

### ISSUE THREAD

**Issue by CzarOfScripts** [helsmy/vscode-autohotkey#4] opened 2021-12-20 08:32 UTC
Code Completion does not work, use the latest version, what information do you need?

**Comment by helsmy** [comment] 2021-12-20 09:26
Not all completion features of old versions are Implemented in current versions, such as property completion at an object varible. So, which type of completion is not working? Just properties or even global completions? More detail of your files will be helpful.

**Comment by CzarOfScripts** [comment] 2021-12-20 10:19
Function completion and parameter hinting did not work, even if the function is in the same file. Now it somehow miraculously picks up everything, even from 'include'. I don't even know what could be the problem.

**Comment by CzarOfScripts** [comment] 2021-12-20 15:23
There were no changes in the files, Code Completion and Function completion does not work again.

**Comment by helsmy** [comment] 2021-12-20 15:28
Could you descript it more detail? Where it happens, which function, code sinppets of it or something.

**Comment by CzarOfScripts** [comment] 2021-12-20 22:09
I do not even know what to answer, one time everything works, I open another time - does not work (I open / close the editor). And in all files.
I want to try to post one of my programs on github, I will leave a link, there will be a code where you can check everything.

**Comment by CzarOfScripts** [comment] 2021-12-21 00:26
https://github.com/Oliver-Patterson/system-monitor

**Comment by helsmy** [comment] 2021-12-21 09:27
I got it. It is caused by path converter. Path is converted incorrect, so include files is not loaded. It will be fixed in next version.

**Comment by CzarOfScripts** [comment] 2021-12-26 17:25
Can you tell me how to make the methods higher than snippets?

![image](https://user-images.githubusercontent.com/78804737/147415569-866ee789-d663-4322-941c-533c61adb2a0.png)

**Comment by helsmy** [comment] 2021-12-26 17:50
1. Press `Ctrl+P` and type `>Usr Settings` 
2. Press `Enter`
3. In search settings type `snippet`
4. Find item `Editor: Snippet Suggestions`
5. In drop down menu select  `bottom`

That's all

**Closed as completed** 2022-04-24 04:44 UTC
