### ISSUE TITLE
Hint doesn't work

### ISSUE THREAD

**Issue by Oliver-Patterson** [helsmy/vscode-autohotkey#14] opened 2021-05-11 11:32 UTC
I write the name of the function, but I am not given the continuation of it:
![image](https://user-images.githubusercontent.com/78804737/117808069-1a713580-b265-11eb-80e1-3f9e1623c943.png)
But if I add it, then the parameters are highlighted:
![image](https://user-images.githubusercontent.com/78804737/117808113-29f07e80-b265-11eb-8a2b-61dd007f2d51.png)

This problem existed even before the 0.5.6 update (in 0.5.5 there was definitely this problem).

**Comment by Oliver-Patterson** [comment] 2021-05-11 11:41
I will add that this function is in include (#Include D:/AutoHotKey/library/extraFunc.ahk).

**Comment by helsmy** [comment] 2021-05-17 04:20
what's the meaning of Hint doesn't work? Code completion doesn't given? But, Signture help works?
And please provide the problem file or more infomation about it.

**Comment by Oliver-Patterson** [comment] 2021-05-18 04:17
"Code completion doesn't given? But, Signture help works?"
Yes!
it does not depend on the file, sometimes there is auto-completion, and sometimes not.  The addition also does not work if the function is declared in the same file.

**Comment by helsmy** [comment] 2021-06-01 10:09
I have fixed some bugs on suffix completion mainly about word splitting. But, I still can't figure out where and how the global symbol completion fails. Any more details about it?

**Comment by Oliver-Patterson** [comment] 2021-06-02 16:22
The function can be declared in the same file and the autocomplete may not see it. It works every other time, sometime it's okay, sometime it's not.

**Comment by helsmy** [comment] 2021-06-03 16:23
It's diffcult to find where is the problem based on information we got so far. How big is you file? Because it takes a few time to get symbols of file,  completion may be fired before parser analyze the whole file.
.

**Comment by Oliver-Patterson** [comment] 2021-06-03 16:28
Как я и говорил ранее, данная проблема может быть в новом файле.
Файл в котором находилась функция был в 1292 строки + еще один в 9302 строк. Но проблема явно же не в этом, ибо подсказка же отображалась. Да и после ожидания обычно ничего не меняется (я знаю, что ему нужно время для анализа).

**Comment by Oliver-Patterson** [comment] 2021-06-04 08:44
![image](https://user-images.githubusercontent.com/78804737/120773087-a7887100-c529-11eb-862b-daefa59cfe03.png)
Here again, 5 minutes have passed since loading VSCode with this file, I think it would have analyzed everything a long time ago. 
Only 3 includes are connected:
![image](https://user-images.githubusercontent.com/78804737/120773193-c6870300-c529-11eb-978f-60d5d1dc6189.png)
extraFunc.ahk: 1292 line
codeProtect.ahk: 16 line
Gdip: 2639 line

While I was clicking on the names of the function in order to open include files, Gdip began to provide autocompletion

**Comment by helsmy** [comment] 2021-06-04 19:55
I got what is missing. It caused by a duplication wrong on code. It will be fixed on the next version. :smile:

**Closed** 2021-06-05 11:05 UTC
